version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: eventsUser
      POSTGRES_PASSWORD: event123
      POSTGRES_DB: RAL_EVENTS
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
    - 8080:8080


volumes:
  postgres_data:
